# Generated by Django 4.0.4 on 2022-06-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_rename_edad_pacientes_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='nombre',
            new_name='Medico',
        ),
    ]
